const newdata = {
    "taskId": "5d2a40c4-814e-4d14-8b53-7a38395ddc07",
    "id": "cc58d578-ab51-4f1d-9ea2-132b2f6d90fd",
    "name": "Vendor Fresh IT",
    "businessControlTypeName": "Due Diligence",
    "businessControlTypeDisplayName": "E",
    "narrative": null,
    "assignedByTitle": null,
    "assignedSubmittedBy": null,
    "dueDate": "2025-02-17T00:00:00",
    "completedDate": "2025-02-17T09:06:24.9475054",
    "evidences": null,
    "comment": null,
    "previousComment": null,
    "elementsAssociated": null,
    "stageId": null,
    "stage": null,
    "taskDescription": "Vendor Fresh IT",
    "associatedElementDataTableViewModel": [],
    "evidenceViewModel": [],
    "userEvidenceViewModel": [],
    "actionViewModel": [],
    "stageActionViewModel": [],
    "taskDraftReviewViewModel": null,
    "totalNumberOfRows": 384,
    "referenceNumber": "E20250217136477",
    "workflowInstanceId": "1dcd4b02-9c4c-4ff3-b4c8-dd7c5bf7cdc7",
    "definationFormJsonForScheduleKri": null,
    "createdDate": "2025-02-17T08:43:28.893",
    "actionType": "Submit",
    "workFlowTypeViewModel": null,
    "stageNumber": 0,
    "currentStageNumber": 6,
    "selectedAction": null,
    "remarks": null,
    "selectedActionId": null,
    "formJsonList": null,
    "controlName": null,
    "controlDescription": null,
    "processName": null,
    "policyName": null,
    "itSystemName": null,
    "url": null,
    "urlStatus": null,
    "selectedTransistionBack": false,
    "referBackToStage": null,
    "referBackToUser": null,
    "amendmentTaskId": null,
    "amendmentReferenceNumber": null,
    "originTaskId": null,
    "originReferenceNumber": null,
    "isSubmitted": true,
    "isProcessChanged": false,
    "isPending": false,
    "title": "Vendor Fresh IT-17/02/2025 02:13 PM",
    "selfAttestationId": null,
    "selfAttestationName": null,
    "isProcessReject": false,
    "processImageComment": null,
    "stages": [],
    "referbackToInitiator": false,
    "referbackStageId": null,
    "additionalUsers": null,
    "allowAmendment": false,
    "controlId": null,
    "processId": null,
    "policyId": null,
    "itSystemId": null,
    "initiatorName": "Amar Patil",
    "initiatorDepartment": "Vendor Fresh IT",
    "initiatorRole": "Testing Branches",
    "initiatorUnit": "",
    "dateOfRaise": "2025-02-17T08:43:28.893",
    "workflowCategory": "DD",
    "riskName": null,
    "riskId": null,
    "unitofMeasurement": null,
    "targetValue": null,
    "baselineValue": null,
    "baselLossType": null,
    "baselBusinessLine": null,
    "kriRiskName": null,
    "personalID": null,
    "strDateOfRaise": "17/02/2025 08:43:28 AM",
    "isCompleted": false,
    "inProgressStageNo": 0,
    "isRejected": false
}

export default newdata;