const summary = [
    {
        "type": null,
        "name": "text-1723623592556",
        "label": "Vendor Name",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "GIEOM",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "select-1723623847936",
        "label": "Department",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Business::Test Z::Test Dept",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "textarea-1723623868177",
        "label": "Office/Registered Address",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Bengaluru",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "date-1723623898192",
        "label": "Due diligence initiation date",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "17-02-2025",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "select-1723623903204",
        "label": "States in which service is proposed to be rendered",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Andra Pradesh,Maharashtra",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "select-1724588912403",
        "label": "Nature of Service",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Document processing (Including KYC)",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1723702757488",
        "label": "Signed Vendor Application form",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1723703394313",
        "label": "Consent Letter for drawing Credit Bureau Reports:  (i) For individual/ proprietorship: Individual/ proprietorship  (ii) For Partnership firm/ LLP: Partnership firm/ LLP and Authorised signatory (iii) For Private Ltd/ Ltd company: Private Ltd/Ltd company and Authorised signatory  (iv) For Any other entities: Any other entity and Authorised signatory",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1723703592332",
        "label": "Self attested copies of KYC Documents (Pan Card, Aadhar Card,Passport, Voter ID - Address Proof, Identity Proof)  (For individual/proprietorship firm: KYC documents for individual and Proprietorship firm For HUF, Partnership firm or Any other entities: KYC documents of HUF, Partnership firm or Any other entities and Authorised signatories) duly verified by bank officials with emp ID",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1723709399230",
        "label": "Payout structure as approved by Bank",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "file-1723709403969",
        "label": "Evidence",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "ScreeNNew.png",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1723709504449",
        "label": "Police Verification Certificate (for collection & repossession vendors)",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "select-1731909026814",
        "label": "Additional documentation",
        "userName": "Amar Patil",
        "time": "2025-02-17T08:43:28.8571266Z",
        "oldValue": null,
        "newValue": "Proprietorship",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1731912498178",
        "label": "Block Diagram (HLD), Approved Network architecture diagram, Approved application architecture diagram.",
        "userName": "Mark Wilson",
        "time": "2025-02-17T08:49:27.1881567Z",
        "oldValue": null,
        "newValue": "No",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1731912925200",
        "label": "Is there any PII data /fields involved? And What is the controls in place for handling sensitive data/ PII?",
        "userName": "Mark Wilson",
        "time": "2025-02-17T08:49:27.1881567Z",
        "oldValue": null,
        "newValue": "No",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1731914824596",
        "label": "What is their plan for disaster recovery and business continuity in case of an incident impacting your organization?",
        "userName": "Mark Wilson",
        "time": "2025-02-17T08:49:27.1881567Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "date-1726737141297",
        "label": "IBA Scrubbing date",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "20-02-2025",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "file-1726737144911",
        "label": "IBA Scrubbing proof",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "ScreeNNew.png",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "select-1726737186729",
        "label": "Department SPOC",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "Branch Management/Testing Branches/Amar Patil : amar",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "date-1726737283431",
        "label": "Date of Assessment",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": null,
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1726737337537",
        "label": "1. Will the outsourcing activity require the service provider to face the customer on behalf of the Bank",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "number-1734419521595",
        "label": "Cost of outsourcing of this activity (annualised) – value of the contract, fees to be paid to the outsourced agency, etc. (A) (INR)",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "1000",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "number-1734419530557",
        "label": "Total operating cost of the Bank (B) (INR)",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "5000",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "number-1734419660330",
        "label": "Percentage of Outsourcing cost vis-a-vis total operating cost",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "20.00",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1727169292077",
        "label": "11. Will the failure or inadequate performance of the service provider impact the brand value/ reputation of the Bank?",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1727169353329",
        "label": "12. Any adverse national level media report or strictures from the High Court or above or any financial sector regulator in the past six months against the activity?",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1727169448819",
        "label": "13. Will the failure or inadequate performance by the service provider have a material impact in meeting its obligations to its stakeholders (customers, regulators and investors) including adverse impact on the customer service?",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "No",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "radio-group-1727169505966",
        "label": "14. Will the failure or inadequate performance by the service provider have a material impact in meeting the regulatory requirements by the Bank?",
        "userName": "Andrew cooper",
        "time": "2025-02-17T08:56:52.0858523Z",
        "oldValue": null,
        "newValue": "Yes",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "file-1726737764065",
        "label": "Upload RMCE Note",
        "userName": "Andrew cooper",
        "time": "2025-02-17T09:06:18.5121289Z",
        "oldValue": null,
        "newValue": "ScreeNNew.png",
        "comment": null,
        "cellName": null
    },
    {
        "type": null,
        "name": "textarea-1726737769092",
        "label": "Remarks",
        "userName": "Andrew cooper",
        "time": "2025-02-17T09:06:18.5121289Z",
        "oldValue": null,
        "newValue": "Approved",
        "comment": null,
        "cellName": null
    }
];

export default summary